kind: Service
apiVersion: v1
metadata:
  name: catalog-api
  labels:
    app: eshop
    service: catalog
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    service: catalog
