kind: Deployment
apiVersion: apps/v1
metadata:
  name: identity
  labels:
    app: eshop
    service: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      service: identity
  template:
    metadata:
      labels:
        app: eshop
        service: identity
    spec:
      containers:
        - name: identity-api
          image: ${REGISTRY:-eshop}/identity.api:${PLATFORM:-linux}-${TAG:-latest}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 80
              path: /liveness
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              port: 80
              path: /hc
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: identity-cm

---

kind: Service
apiVersion: v1
metadata:
  name: identity-api
  labels:
    app: eshop
    service: identity
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    service: identity

---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: identity
  labels:
    app: eshop
    service: identity
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
        - path: /identity
          backend:
            serviceName: identity-api
            servicePort: 80