kind: Deployment
apiVersion: apps/v1
metadata:
  name: signalr
  labels:
    app: eshop
    service: signalr
spec:
  replicas: 1
  selector:
    matchLabels:
      service: signalr
  template:
    metadata:
      labels:
        app: eshop
        service: signalr
    spec:
      containers:
        - name: ordering-signalrhub
          image: ${REGISTRY:-eshop}/ordering.signalrhub:${PLATFORM:-linux}-${TAG:-latest}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 80
              path: /liveness
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              port: 80
              path: /hc
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: signalr-cm

---

apiVersion: v1
kind: Service
metadata:
  name: ordering-signalrhub
  labels:
    app: eshop
    service: signalr
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    service: signalr
