kind: Deployment
apiVersion: apps/v1
metadata:
  name: webspa
  labels:
    app: eshop
    service: webspa
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webspa
  template:
    metadata:
      labels:
        app: eshop
        service: webspa
    spec:
      containers:
        - name: webspa
          image: ${REGISTRY:-eshop}/webspa:${PLATFORM:-linux}-${TAG:-latest}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: webspa-cm

---

kind: Service
apiVersion: v1
metadata:
  name: webspa
  labels:
    app: eshop
    service: webspa
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    service: webspa

---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: webspa
  labels:
    app: eshop
    service: webspa
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: webspa
            servicePort: 80