kind: ConfigMap
apiVersion: v1
metadata:
  name: ordering-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: ordering
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  IdentityUrl: http://identity-api
  IdentityUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30008
  SeqServerUrl: http://seq
  SqlConnectionString: Server=sqldata;Database=Microsoft.eShopOnDapr.Services.OrderingDb;User Id=sa;Password=Pass@word

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: ordering
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: ordering
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ordering
  template:
    metadata:
      labels:
        app: eshop
        service: ordering
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "ordering-api"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
        dapr.io/log-as-json: "true"
    spec:
      containers:
        - name: ordering-api
          image: eshopdapr/ordering.api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: ordering-cm

---

apiVersion: v1
kind: Service
metadata:
  name: ordering-api
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: ordering
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
      protocol: TCP
      name: http
  selector:
    service: ordering
